apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: {{ .Values.image.repository }}{{ .Values.environment }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: cloud-secret