FROM node:16.16.0

WORKDIR /frontend

COPY ./frontend/vue/package*.json ./

RUN npm install
COPY ./frontend/vue ./

RUN npm run build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY /frontend/dist .

RUN ls -R /frontend/vue/dist
RUN ls -R /