version: '3'
services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: ./Dockerfile-dev
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile-dev
    container_name: frontend
    volumes:
      - ./frontend/vue:/frontend
      - /frontend/node_modules/
    ports:
      - "3000:3000"
#    depends_on:
#      - backend-dev