version: '3'
services:
  backend-container:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
  frontend-container:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "80:80"
