version: '3'
services:
  jdk-container:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
  node-container:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
