version: '3'
services:
  backend-prod:
    build:
      context: ./backend
      dockerfile: ./Dockerfile-prod
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile-prod
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "80:80"
    depends_on:
      - backend-prod