# Build de l'appli
FROM maven:3.8.4-openjdk-17-slim as builder

WORKDIR /backend

COPY ./ ./

RUN mvn clean package

# Run de l'appli
FROM openjdk:17.0.1-jdk-slim

RUN pwd
RUN ls -R

COPY --from=builder ./backend/target/backend-1.0.0.jar backend-1.0.0.jar

EXPOSE 8080

CMD ["java", "-jar", "backend-1.0.0.jar"]