apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: ghcr.io/cripsoo/projetcloud/frontend-recette:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: cloud-secret