version: "3.9"
services:
  app:
    build: .
    container_name: outils
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./terraform:/terraform/
    stdin_open: true
    tty: true
