version: "3.9"
services:
  app:
    build: .
    container_name: outils
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kubectl/:/kubectl/
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
