apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: {{ .Values.image.repository }}{{ .Values.global.environment }}:{{ .Values.image.tag }}
          env:
            - name: VUE_APP_DOMAIN
              value: "https://{{ .Values.global.environment }}.groupe6.froissant.work"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: cloud-secret