name: Build-and-Push-to-Container-Registry-Recette

on:
  workflow_run:
    workflows: ["Tests-Unitaires-Backend"]
    types:
      - completed

jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: backend/Dockerfile-prod
          push: true
          tags: ghcr.io/${{ github.actor }}/projetcloud/backend-recette:latest

  frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: frontend/Dockerfile-prod
          push: true
          tags: ghcr.io/${{ github.actor }}/projetcloud/frontend-recette:latest
