name: Build-and-Push-to-Container-Registry-Recette

on:
  workflow_run:
    workflows: ["Tests-Unitaires-Backend"]
    types:
      - completed

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Java application
        run: |
          ./mvnw clean package

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/projetcloud/backend:latest .
          docker push ghcr.io/projetcloud/backend:latest

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Vue.js application
        run: |
          cd frontend/vue
          npm install
          npm run build

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/projetcloud/frontend:latest .
          docker push ghcr.io/projetcloud/frontend:latest
