name: Deploy to Env

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Choisir l'environnement"
        required: true
        options:
          - recette
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Connexion Azure
        uses: azure/CLI@v1
        with:
          azcliversion: 2.55.0
          inlineScript: |
            az login --user ${{ secrets.AZURE_LOGIN }} --password ${{ secrets.AZURE_PASSWORD }}

      - name: Installer kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.4'

      - name: Installer Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.1'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.5

      - name: Initialisation Terraform
        run: |
          sudo az login --user ${{ secrets.AZURE_LOGIN }} --password ${{ secrets.AZURE_PASSWORD }}
          cd $GITHUB_WORKSPACE/outils/terraform
          sudo terraform init -backend-config=configs/${{ github.event.inputs.environment }}.conf

      - name: Appliquer Terraform
        id: deploy-terraform
        run: |
          sudo az login --user ${{ secrets.AZURE_LOGIN }} --password ${{ secrets.AZURE_PASSWORD }}
          cd $GITHUB_WORKSPACE/outils/terraform
          sudo terraform apply -var="githubToken=${{ secrets.GITHUB_TOKEN }}" -var="env_name=${{ github.event.inputs.environment }}" -auto-approve
          KUBE_CONFIG=$(sudo terraform output -json kubeconfig)
          echo "::set-output name=kube-config::$KUBE_CONFIG"

      - name:
        id: get-ip
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ steps.deploy-terraform.outputs.kube-config }}
        with:
          args: echo "::set-output name=ingress-ip::$(kubectl get services ingress-controller-ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installer les dépendances python
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Mettre à jour l'ip du DNS
        run: python $GITHUB_WORKSPACE/outils/terraform/scripts ${{ secrets.GANDI_API_KEY }} ${{ steps.get-ip.outputs.ingress-ip }}