name: testGandi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Connexion Azure
        uses: azure/CLI@v1
        with:
          azcliversion: 2.55.0
          inlineScript: |
            az login --user ${{ secrets.AZURE_LOGIN }} --password ${{ secrets.AZURE_PASSWORD }}
            az aks get-credentials --resource-group ProjetCloud-recette --name AKS-recette

      - name: Installer kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.4'

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installer les dépendances python
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Récupérer l'IP du service
        id: get_ip
        shell: bash
        run: |
          sudo az login --user ${{ secrets.AZURE_LOGIN }} --password ${{ secrets.AZURE_PASSWORD }}
          sudo az aks get-credentials --resource-group ProjetCloud-recette --name AKS-recette
          IP=$(sudo kubectl get services ingress-controller-ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "On met à jour l'ip: $IP"
          python $GITHUB_WORKSPACE/outils/terraform/scripts/update_api.py ${{ secrets.GANDI_API_KEY }} $IP