name: Tests-Unitaires-Backend

on:
  push:
    branches: ["develop", "prod"]
  pull_request:
    branches: ["develop", "prod"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test --file pom.xml
